version: '3.9'
services:
  mysql:
    image: mysql:8.0
    restart: "no"
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      PGTZ: 'Asia/Ho_Chi_Minh'
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db/mysql:/data/mysql
    env_file:
      - .env